/// <auto-generated>
///***************************************************///
///                                                   ///
/// This file is auto-generated by UnityTaskGenerator ///
///            DO NOT manually modify it!             ///
///                                                   ///
///***************************************************///
/// </auto-generated>

using System.Collections.Generic;

namespace EncosyTower.Tasks
{
    public static partial class UnityTaskExtensions
    {
        /// <summary>
        /// Awaits every task in <paramref name="tasks"/>, as <c>UnityTask.WhenAll(tasks)</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this UnityTask[] tasks)
            => UnityTask.WhenAll(tasks).GetAwaiter();

        /// <summary>
        /// Awaits every task in <paramref name="tasks"/>, as <c>UnityTask.WhenAll(tasks)</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this IEnumerable<UnityTask> tasks)
            => UnityTask.WhenAll(tasks).GetAwaiter();

        /// <summary>
        /// Awaits every task in <paramref name="tasks"/>, as <c>UnityTask.WhenAll(tasks)</c> does.
        /// </summary>
        /// <typeparam name="T">The result type of the tasks.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<T[]>.Awaiter GetAwaiter<T>(this UnityTask<T>[] tasks)
            => UnityTask.WhenAll(tasks).GetAwaiter();

        /// <summary>
        /// Awaits every task in <paramref name="tasks"/>, as <c>UnityTask.WhenAll(tasks)</c> does.
        /// </summary>
        /// <typeparam name="T">The result type of the tasks.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<T[]>.Awaiter GetAwaiter<T>(this IEnumerable<UnityTask<T>> tasks)
            => UnityTask.WhenAll(tasks).GetAwaiter();

        /// <summary>
        /// Awaits the 2 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2).GetAwaiter();

        /// <summary>
        /// Awaits the 2 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2)>.Awaiter GetAwaiter<T1, T2>(this (UnityTask<T1> task1, UnityTask<T2> task2) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2).GetAwaiter();

        /// <summary>
        /// Awaits the 3 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3).GetAwaiter();

        /// <summary>
        /// Awaits the 3 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3)>.Awaiter GetAwaiter<T1, T2, T3>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3).GetAwaiter();

        /// <summary>
        /// Awaits the 4 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4).GetAwaiter();

        /// <summary>
        /// Awaits the 4 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4)>.Awaiter GetAwaiter<T1, T2, T3, T4>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4).GetAwaiter();

        /// <summary>
        /// Awaits the 5 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5).GetAwaiter();

        /// <summary>
        /// Awaits the 5 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5).GetAwaiter();

        /// <summary>
        /// Awaits the 6 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6).GetAwaiter();

        /// <summary>
        /// Awaits the 6 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6).GetAwaiter();

        /// <summary>
        /// Awaits the 7 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7).GetAwaiter();

        /// <summary>
        /// Awaits the 7 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7).GetAwaiter();

        /// <summary>
        /// Awaits the 8 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8).GetAwaiter();

        /// <summary>
        /// Awaits the 8 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8).GetAwaiter();

        /// <summary>
        /// Awaits the 9 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8, UnityTask task9) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9).GetAwaiter();

        /// <summary>
        /// Awaits the 9 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <typeparam name="T9">The result type of task 9.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8, T9)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8, T9>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8, UnityTask<T9> task9) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9).GetAwaiter();

        /// <summary>
        /// Awaits the 10 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8, UnityTask task9, UnityTask task10) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10).GetAwaiter();

        /// <summary>
        /// Awaits the 10 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <typeparam name="T9">The result type of task 9.</typeparam>
        /// <typeparam name="T10">The result type of task 10.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8, UnityTask<T9> task9, UnityTask<T10> task10) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10).GetAwaiter();

        /// <summary>
        /// Awaits the 11 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8, UnityTask task9, UnityTask task10, UnityTask task11) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11).GetAwaiter();

        /// <summary>
        /// Awaits the 11 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <typeparam name="T9">The result type of task 9.</typeparam>
        /// <typeparam name="T10">The result type of task 10.</typeparam>
        /// <typeparam name="T11">The result type of task 11.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8, UnityTask<T9> task9, UnityTask<T10> task10, UnityTask<T11> task11) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11).GetAwaiter();

        /// <summary>
        /// Awaits the 12 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8, UnityTask task9, UnityTask task10, UnityTask task11, UnityTask task12) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12).GetAwaiter();

        /// <summary>
        /// Awaits the 12 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <typeparam name="T9">The result type of task 9.</typeparam>
        /// <typeparam name="T10">The result type of task 10.</typeparam>
        /// <typeparam name="T11">The result type of task 11.</typeparam>
        /// <typeparam name="T12">The result type of task 12.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8, UnityTask<T9> task9, UnityTask<T10> task10, UnityTask<T11> task11, UnityTask<T12> task12) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12).GetAwaiter();

        /// <summary>
        /// Awaits the 13 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8, UnityTask task9, UnityTask task10, UnityTask task11, UnityTask task12, UnityTask task13) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12, tasks.task13).GetAwaiter();

        /// <summary>
        /// Awaits the 13 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <typeparam name="T9">The result type of task 9.</typeparam>
        /// <typeparam name="T10">The result type of task 10.</typeparam>
        /// <typeparam name="T11">The result type of task 11.</typeparam>
        /// <typeparam name="T12">The result type of task 12.</typeparam>
        /// <typeparam name="T13">The result type of task 13.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8, UnityTask<T9> task9, UnityTask<T10> task10, UnityTask<T11> task11, UnityTask<T12> task12, UnityTask<T13> task13) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12, tasks.task13).GetAwaiter();

        /// <summary>
        /// Awaits the 14 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8, UnityTask task9, UnityTask task10, UnityTask task11, UnityTask task12, UnityTask task13, UnityTask task14) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12, tasks.task13, tasks.task14).GetAwaiter();

        /// <summary>
        /// Awaits the 14 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <typeparam name="T9">The result type of task 9.</typeparam>
        /// <typeparam name="T10">The result type of task 10.</typeparam>
        /// <typeparam name="T11">The result type of task 11.</typeparam>
        /// <typeparam name="T12">The result type of task 12.</typeparam>
        /// <typeparam name="T13">The result type of task 13.</typeparam>
        /// <typeparam name="T14">The result type of task 14.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8, UnityTask<T9> task9, UnityTask<T10> task10, UnityTask<T11> task11, UnityTask<T12> task12, UnityTask<T13> task13, UnityTask<T14> task14) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12, tasks.task13, tasks.task14).GetAwaiter();

        /// <summary>
        /// Awaits the 15 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter for the combined task.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask.Awaiter GetAwaiter(this (UnityTask task1, UnityTask task2, UnityTask task3, UnityTask task4, UnityTask task5, UnityTask task6, UnityTask task7, UnityTask task8, UnityTask task9, UnityTask task10, UnityTask task11, UnityTask task12, UnityTask task13, UnityTask task14, UnityTask task15) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12, tasks.task13, tasks.task14, tasks.task15).GetAwaiter();

        /// <summary>
        /// Awaits the 15 tasks of <paramref name="tasks"/>, as <c>UnityTask.WhenAll</c> does.
        /// </summary>
        /// <typeparam name="T1">The result type of task 1.</typeparam>
        /// <typeparam name="T2">The result type of task 2.</typeparam>
        /// <typeparam name="T3">The result type of task 3.</typeparam>
        /// <typeparam name="T4">The result type of task 4.</typeparam>
        /// <typeparam name="T5">The result type of task 5.</typeparam>
        /// <typeparam name="T6">The result type of task 6.</typeparam>
        /// <typeparam name="T7">The result type of task 7.</typeparam>
        /// <typeparam name="T8">The result type of task 8.</typeparam>
        /// <typeparam name="T9">The result type of task 9.</typeparam>
        /// <typeparam name="T10">The result type of task 10.</typeparam>
        /// <typeparam name="T11">The result type of task 11.</typeparam>
        /// <typeparam name="T12">The result type of task 12.</typeparam>
        /// <typeparam name="T13">The result type of task 13.</typeparam>
        /// <typeparam name="T14">The result type of task 14.</typeparam>
        /// <typeparam name="T15">The result type of task 15.</typeparam>
        /// <param name="tasks">The tasks to await.</param>
        /// <returns>An awaiter whose result holds each result at its tuple position.</returns>
        /// <remarks>
        /// <para>
        /// <b>Counterparts:</b> UniTask: <c>UniTaskExtensions.GetAwaiter</c>; Unity: none.
        /// </para>
        /// </remarks>
        public static UnityTask<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)>.Awaiter GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(this (UnityTask<T1> task1, UnityTask<T2> task2, UnityTask<T3> task3, UnityTask<T4> task4, UnityTask<T5> task5, UnityTask<T6> task6, UnityTask<T7> task7, UnityTask<T8> task8, UnityTask<T9> task9, UnityTask<T10> task10, UnityTask<T11> task11, UnityTask<T12> task12, UnityTask<T13> task13, UnityTask<T14> task14, UnityTask<T15> task15) tasks)
            => UnityTask.WhenAll(tasks.task1, tasks.task2, tasks.task3, tasks.task4, tasks.task5, tasks.task6, tasks.task7, tasks.task8, tasks.task9, tasks.task10, tasks.task11, tasks.task12, tasks.task13, tasks.task14, tasks.task15).GetAwaiter();
    }
}
