[assembly: global::EncosyTower.CodeGen.SkipSourceGeneratorsForAssembly]
[assembly: global::EncosyTower.CodeGen.AllowSourceGeneratorsForAssembly("EncosyTower.PolyEnumStructs")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("EncosyTower.DevTools")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("EncosyTower.Data.Authoring")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("EncosyTower.Tests.EditorMode")]
